version: "3"

services:
  suomen-botti:
    container_name: suomen-botti
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - BP_LOGIN_LIMIT=10
      - SUOMEN_BOTTI_TG_TOKEN=${SUOMEN_BOTTI_TG_TOKEN}
    networks:
      - bp_net
    restart: on-failure

networks:
  bp_net:
    driver: bridge